### ISSUE TITLE
Update to ELEMENT DESCRIPTOR column contents for 3-10-026

### ISSUE THREAD

**Issue by SimonElliottEUM** [wmo-im/BUFR4#153]
### Initial request

In BUFR Table D, sequence 3-10-026 has as its third component the descriptor 0-08-021 for "Time significance".

The ELEMENT DESCRIPTOR column gives "= 17 Start of phenomenon" 

In practice this element may need to indicate the "Nominal reporting time", which has a value of 25. The ELEMENT DESCRIPTOR field should be updated accordingly.

### Amendment details

Change ELEMENT DESCRIPTOR column contents for the third entry (0-08-021) in BUFR Table D sequence 3-10-026 from:
= 17 Start of phenomenon

to

= 17 Start of phenomenon, or 25 Nominal reporting time

### Comments

This change will reflect the differing use of the encoding sequence be different data providers.

The sequence itself does not need to be changed.

### Requestor(s)

Enter list of requestors.

### Stakeholder(s)

Simon Elliott, on behalf of EUMETSAT and its Radio Occultation Meteorology Satellite Application Facility (ROM SAF).

### Publication(s)

Manual on Codes (WMO-No. 306), Volume I.2, BUFR table D sequence 3 10 026

### Expected impact of change

LOW

### Collaborators

@marijanacrepulja and @efucile advised on the right approach to make this change.

**Comment by amilan17** [comment]
[https://github.com/wmo-im/CCT/wiki/Teleconference.25.26.April.2023](https://github.com/wmo-im/CCT/wiki/Teleconference.25.26.April.2023) notes: 

*   (Marijana) No change in the sequence, just documenting another user case for this sequence. It's a simple addition to the descriptor (Jeff) We noticed that the times were offset for the same data from Eumetstat and KMI, because the two centers were using a different way of using the time. The purpose is to indicate that different types of time can be reported. (Sibylle) I support this proposal, the descriptors are not part of the regulations and it's useful to have the descriptor;

**Comment by amilan17** [comment]
@marijanacrepulja @SimonElliottEUM PR is ready for your review

**Comment by SimonElliottEUM** [comment]
@amilan17 @marijanacrepulja I have checked the updated text shown in the "Files changed" tab, and it is correct

**Comment by amilan17** [comment]
[https://github.com/wmo-im/CCT/wiki/Teleconference.13.July.2023](https://github.com/wmo-im/CCT/wiki/Teleconference.13.July.2023) notes:

branch is ready
